Acerva.Web/Models/Home/AnexoNoticiaViewModel.cs
namespace Acerva.Web.Models.Home
{
    public class AnexoNoticiaViewModel
    {
        public virtual int Codigo { get; set; }
        public virtual string Titulo { get; set; }
        public virtual string NomeArquivo { get; set; }
    }
}

Acerva.Web/Controllers/ArtigoController.cs
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Principal;
using System.Web.Mvc;
using AutoMapper;
using Acerva.Infra.Repositorios;
using Acerva.Infra.Web;
using Acerva.Modelo;
using Acerva.Web.Extensions;
using Acerva.Web.Models;
using Acerva.Web.Models.CadastroArtigos;
using FluentValidation;
using log4net;
using Microsoft.AspNet.Identity;

namespace Acerva.Web.Controllers
{
    [Authorize]
    [AcervaAuthorize(Roles = "ADMIN, DIRETOR")]
    public class ArtigoController : ApplicationBaseController
    {
        private static readonly ILog Log =
            LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private readonly ICadastroArtigos _cadastroArtigos;
        private readonly IValidator<Artigo> _validator;
        private readonly ICadastroUsuarios _cadastroUsuarios;
        private readonly IIdentity _user;
        
        public ArtigoController(ICadastroArtigos cadastroArtigos, IValidator<Artigo> validator, 
            IPrincipal user, ICadastroUsuarios cadastroUsuarios) : base(cadastroUsuarios)
        {
            _cadastroArtigos = cadastroArtigos;
            _validator = validator;
            _cadastroUsuarios = cadastroUsuarios;
            _user = user.Identity;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BuscaParaListagem()
        {
            var listaArtigosJson = _cadastroArtigos.BuscaParaListagem()
                .Select(Mapper.Map<ArtigoViewModel>);
            return new JsonNetResult(listaArtigosJson);
        }

        public ActionResult BuscaAnexos(int codigoArtigo)
        {
            var artigo = _cadastroArtigos.Busca(codigoArtigo);

            var listaAnexosJson = artigo.Anexos
                .Select(Mapper.Map<AnexoArtigoViewModel>);
            return new JsonNetResult(listaAnexosJson);
        }

        public ActionResult BuscaTiposDominio()
        {
            var categoriasJson = _cadastroArtigos.BuscaCategorias()
                .Select(Mapper.Map<CategoriaArtigoViewModel>);

            return new JsonNetResult(new
            {
                Categorias = categoriasJson
            });
        }

        public ActionResult Busca(int codigo)
        {
            var artigo = _cadastroArtigos.Busca(codigo);
            var artigoJson = Mapper.Map<ArtigoViewModel>(artigo);
            return new JsonNetResult(artigoJson);
        }

        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult Salva([JsonBinder]ArtigoViewModel artigoViewModel)
        {
            Log.InfoFormat("Usuário está salvando a artigo {0} de código {1}", artigoViewModel.Titulo, artigoViewModel.Codigo);

            var ehNovo = artigoViewModel.Codigo == 0;
            var artigo = ehNovo ? new Artigo() : _cadastroArtigos.Busca(artigoViewModel.Codigo);

            artigoViewModel.Titulo = artigoViewModel.Titulo.Trim();

            Mapper.Map(artigoViewModel, artigo);

            var usuarioLogado = HttpContext.User;
            var usuarioLogadoBd = usuarioLogado.Identity.IsAuthenticated ? _cadastroUsuarios.Busca(usuarioLogado.Identity.GetUserId()) : null;
            artigo.Usuario = usuarioLogadoBd;

            var validacao = _validator.Validate(artigo);
            if (!validacao.IsValid)
                return RetornaJsonDeAlerta(validacao.GeraListaHtmlDeValidacoes());

            if (ExisteComMesmoTitulo(artigo))
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Já existe uma artigo com o nome {0:unsafe}", artigo.Titulo));

            artigo.DataHora = artigoViewModel.DataHora ?? DateTime.Now;

            if (ehNovo)
                _cadastroArtigos.Salva(artigo);

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Artigo <a href='{0}#/Edit/{1}'>{2}</a> foi salvo com sucesso", Url.Action("Index"), artigo.Codigo, artigo.Titulo),
                "Artigo salvo");

            return new JsonNetResult(new { growlMessage });
        }


        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult ExcluiAnexo(int codigoAnexo)
        {
            var anexo = _cadastroArtigos.BuscaAnexo(codigoAnexo);

            if (anexo == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Arquivo não encontrado"));

            var caminhoCompleto= Path.Combine(Server.MapPath("~/Content/Aplicacao/anexos/artigos/" + anexo.Artigo.Codigo), anexo.NomeArquivo);
            try
            {
                if (System.IO.File.Exists(caminhoCompleto))
                {
                    System.IO.File.Delete(caminhoCompleto);
                }
                _cadastroArtigos.ExcluiAnexo(anexo);
            }
            catch
            {
                RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Erro ao excluir anexo!"));
            }

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Anexo {0} excluído com sucesso", anexo.NomeArquivo), "Anexo excluído");

            return new JsonNetResult(new { growlMessage });
        }

        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult SalvaAnexo(int codigoArtigo, string titulo)
        {
            if (Request.Files == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Nenhum arquivo anexado"));

            var artigo = _cadastroArtigos.Busca(codigoArtigo);
            if (artigo == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Artigo não encontrado"));

            if (Request.Files.Count == 0)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Nenhum arquivo anexado"));

            var file = Request.Files[0];
            if (file == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Nenhum arquivo anexado"));

            var actualFileName = file.FileName;

            if (artigo.Anexos.Any(a => a.NomeArquivo == actualFileName))
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Já existe um anexo com este nome para este artigo!"));

            try
            {
                var path = Server.MapPath("~/Content/Aplicacao/anexos/artigos/" + codigoArtigo);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                var pathCompleto = Path.Combine(path, actualFileName);
                file.SaveAs(pathCompleto);

                var anexo = new AnexoArtigo
                {
                    Artigo = artigo,
                    NomeArquivo = actualFileName,
                    Titulo = titulo
                };

                _cadastroArtigos.SalvaAnexo(anexo);
            }
            catch (Exception)
            {
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Erro ao anexar arquivo"));
            }

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Anexo {0} salvo com sucesso", actualFileName), "Anexo salvo");

            return new JsonNetResult(new { growlMessage });
        }

        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult AlteraAtivacao(int id, bool ativo)
        {
            var prefixoOperacao = ativo ? string.Empty : "des";
            Log.InfoFormat("Usuário {0} está {1}atividando a artigo de id {2}", _user.Name, prefixoOperacao, id);

            var artigo = _cadastroArtigos.Busca(id);
            artigo.Ativo = ativo;

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Artigo <a href='{0}#/Edit/{1}'>{2}</a> foi {3}ativado com sucesso", Url.Action("Index"), artigo.Codigo, artigo.Codigo, prefixoOperacao),
                string.Format("Artigo {0}ativado", prefixoOperacao));

            return new JsonNetResult(new { growlMessage });
        }

        private static ActionResult RetornaJsonDeAlerta(string mensagem)
        {
            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Warning, mensagem, "Artigo não salvo");

            return new JsonNetResult(new { growlMessage }, statusCode: JsonNetResult.HttpBadRequest);
        }

        private bool ExisteComMesmoTitulo(Artigo artigo)
        {
            var nomeUpper = artigo.Titulo.ToUpperInvariant();
            var temComMesmoTitulo = _cadastroArtigos
                .BuscaTodos()
                .Any(e => e.Titulo.ToUpperInvariant() == nomeUpper && e.Codigo != artigo.Codigo && artigo.Categoria.Codigo == e.Categoria.Codigo);

            return temComMesmoTitulo;
        }
    }
}

Acerva.Web/Controllers/NoticiaController.cs
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Principal;
using System.Web.Mvc;
using AutoMapper;
using Acerva.Infra.Repositorios;
using Acerva.Infra.Web;
using Acerva.Modelo;
using Acerva.Web.Extensions;
using Acerva.Web.Models;
using Acerva.Web.Models.CadastroNoticias;
using FluentValidation;
using log4net;

namespace Acerva.Web.Controllers
{
    [Authorize]
    [AcervaAuthorize(Roles = "ADMIN, DIRETOR")]
    public class NoticiaController : ApplicationBaseController
    {
        private static readonly ILog Log =
            LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private readonly ICadastroNoticias _cadastroNoticias;
        private readonly IValidator<Noticia> _validator;
        private readonly IIdentity _user;
        
        public NoticiaController(ICadastroNoticias cadastroNoticias, IValidator<Noticia> validator, 
            IPrincipal user, ICadastroUsuarios cadastroUsuarios) : base(cadastroUsuarios)
        {
            _cadastroNoticias = cadastroNoticias;
            _validator = validator;
            _user = user.Identity;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BuscaParaListagem()
        {
            var listaNoticiasJson = _cadastroNoticias.BuscaParaListagem()
                .Select(Mapper.Map<NoticiaViewModel>);
            return new JsonNetResult(listaNoticiasJson);
        }

        public ActionResult BuscaTiposDominio()
        {
            return new JsonNetResult(new
            {
                
            });
        }

        public ActionResult Busca(int codigo)
        {
            var noticia = _cadastroNoticias.Busca(codigo);
            var noticiaJson = Mapper.Map<NoticiaViewModel>(noticia);
            return new JsonNetResult(noticiaJson);
        }

        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult Salva([JsonBinder]NoticiaViewModel noticiaViewModel)
        {
            Log.InfoFormat("Usuário está salvando a notícia {0} de código {1}", noticiaViewModel.Titulo, noticiaViewModel.Codigo);

            var ehNovo = noticiaViewModel.Codigo == 0;
            var noticia = ehNovo ? new Noticia() : _cadastroNoticias.Busca(noticiaViewModel.Codigo);

            noticiaViewModel.Titulo = noticiaViewModel.Titulo.Trim();

            Mapper.Map(noticiaViewModel, noticia);

            var validacao = _validator.Validate(noticia);
            if (!validacao.IsValid)
                return RetornaJsonDeAlerta(validacao.GeraListaHtmlDeValidacoes());

            if (ExisteComMesmoNome(noticia))
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Já existe uma notícia com o nome {0:unsafe}", noticia.Titulo));

            _cadastroNoticias.Salva(noticia);

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Notícia <a href='{0}#/Edit/{1}'>{2}</a> foi salva com sucesso", Url.Action("Index"), noticia.Codigo, noticia.Titulo),
                "Notícia salva");

            return new JsonNetResult(new { growlMessage });
        }
        
        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult AlteraAtivacao(int id, bool ativo)
        {
            var prefixoOperacao = ativo ? string.Empty : "des";
            Log.InfoFormat("Usuário {0} está {1}atividando a notícia de id {2}", _user.Name, prefixoOperacao, id);

            var noticia = _cadastroNoticias.Busca(id);
            noticia.Ativo = ativo;

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Notícia <a href='{0}#/Edit/{1}'>{2}</a> foi {3}ativado com sucesso", Url.Action("Index"), noticia.Codigo, noticia.Titulo, prefixoOperacao),
                string.Format("Notícia {0}ativada", prefixoOperacao));

            return new JsonNetResult(new { growlMessage });
        }

        private static ActionResult RetornaJsonDeAlerta(string mensagem)
        {
            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Warning, mensagem, "Notícia não salva");

            return new JsonNetResult(new { growlMessage }, statusCode: JsonNetResult.HttpBadRequest);
        }

        private bool ExisteComMesmoNome(Noticia noticia)
        {
            var nomeUpper = noticia.Titulo.ToUpperInvariant();
            var temComMesmoNome = _cadastroNoticias
                .BuscaTodas()
                .Any(e => e.Titulo.ToUpperInvariant() == nomeUpper && e.Codigo != noticia.Codigo);

            return temComMesmoNome;
        }

        public ActionResult BuscaAnexos(int codigoNoticia)
        {
            var noticia = _cadastroNoticias.Busca(codigoNoticia);

            var listaAnexosJson = noticia.Anexos
                .Select(Mapper.Map<AnexoNoticiaViewModel>);
            return new JsonNetResult(listaAnexosJson);
        }



        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult ExcluiAnexo(int codigoAnexo)
        {
            var anexo = _cadastroNoticias.BuscaAnexo(codigoAnexo);

            if (anexo == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Arquivo não encontrado"));

            var caminhoCompleto = Path.Combine(Server.MapPath("~/Content/Aplicacao/anexos/noticias/" + anexo.Noticia.Codigo), anexo.NomeArquivo);
            try
            {
                if (System.IO.File.Exists(caminhoCompleto))
                {
                    System.IO.File.Delete(caminhoCompleto);
                }
                _cadastroNoticias.ExcluiAnexo(anexo);
            }
            catch
            {
                RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Erro ao excluir anexo!"));
            }

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Anexo {0} excluído com sucesso", anexo.NomeArquivo), "Anexo excluído");

            return new JsonNetResult(new { growlMessage });
        }

        [Transacao]
        [HttpPost]
        [ValidateAjaxAntiForgeryToken]
        public ActionResult SalvaAnexo(int codigoNoticia, string titulo)
        {
            if (Request.Files == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Nenhum arquivo anexado"));

            var noticia = _cadastroNoticias.Busca(codigoNoticia);
            if (noticia == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Notícia não encontrada"));

            if (Request.Files.Count == 0)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Nenhum arquivo anexado"));

            var file = Request.Files[0];
            if (file == null)
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Nenhum arquivo anexado"));

            var actualFileName = file.FileName;

            if (noticia.Anexos.Any(a => a.NomeArquivo == actualFileName))
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Já existe um anexo com este nome para esta notícia!"));

            try
            {
                var path = Server.MapPath("~/Content/Aplicacao/anexos/noticias/" + codigoNoticia);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                var pathCompleto = Path.Combine(path, actualFileName);
                file.SaveAs(pathCompleto);

                var anexo = new AnexoNoticia
                {
                    Noticia = noticia,
                    NomeArquivo = actualFileName,
                    Titulo = titulo
                };

                _cadastroNoticias.SalvaAnexo(anexo);
            }
            catch (Exception)
            {
                return RetornaJsonDeAlerta(string.Format(HtmlEncodeFormatProvider.Instance, "Erro ao anexar arquivo"));
            }

            var growlMessage = new GrowlMessage(GrowlMessageSeverity.Success,
                string.Format("Anexo {0} salvo com sucesso", actualFileName), "Anexo salvo");

            return new JsonNetResult(new { growlMessage });
        }
    }
}

Acerva.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h4>@ViewBag.Title</h4>
<h5>@ViewBag.Message</h5>

Acerva.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contatos";
}
<h4>@ViewBag.Title</h4>
<h5>@ViewBag.Message</h5>

<address>
    ACervA Carioca - Associação dos Cervejeiros Artesanais Cariocas<br />
    Avenida Rio Branco, nº 26, Centro, Rio de Janeiro, RJ, CEP 20090-001.<br />
    @*<abbr title="Facebook">Tel.:</abbr> +55 21 XXXXXXXXXX*@
</address>

<address>
    <strong>E-mail:</strong> <a href="mailto:contato@acervacarioca.com.br">contato@acervacarioca.com.br</a>
</address>

<div>
    Curta nossa página no Facebook (<a href="http://facebook.com/AcervaRJ" target="_blank">@@AcervaRJ</a>): <br/>
    <a href="http://facebook.com/AcervaRJ" target="_blank"><img src="@Url.Content("~/Content/Aplicacao/images/like_facebook.png")" style="height: 40px;" alt="Curta nossa página no Facebook"/></a>
</div>

Acerva.Web/Views/Home/Index.cshtml
@using Acerva.Modelo
@using Acerva.Web.Models
@using Microsoft.Owin.Security
@model global::Acerva.Web.Models.Home.UsuarioRegistroViewModel
@{
    ViewBag.Title = "Início";
    ViewBag.AngularApp = "acerva.inicio";
    var action = ViewContext.RouteData.GetRequiredString("action");
    var id = ViewContext.RouteData.Values["id"];
}

<div ng-view ng-cloak></div>
@Html.AntiForgeryToken()
<script type="text/ng-template" id="index.html">
    <div class="row">
        <div class="col-sm-9">
            @Html.Partial("_PaginaInicial")
        </div>
        <div class="col-sm-3" style="margin-top: 20px;">
            @if (!Request.IsAuthenticated)
            {
                <div class="row">
                    <div class="panel panel-info">
                        <div class="panel-body">
                            <a href="@Url.Action("Register", "Account")"><h4 class="text-center">Quero me associar!</h4></a>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="panel panel-info">
                        <div class="panel-body">
                            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                            {
                                @Html.AntiForgeryToken()
                                <h4>Login de associado</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Email, new { @class = "col-md-4 control-label" })
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(m => m.Password, new { @class = "col-md-4 control-label" })
                                    <div class="col-md-8">
                                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-8">
                                        <div class="checkbox" style="margin-left: 20px;">
                                            @Html.CheckBox("RememberMe")
                                            <label>Lembrar de mim?</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-8">
                                        <input type="submit" value="Login" class="btn btn-primary" />
                                    </div>
                                </div>
                                <p class="text-center">
                                    @Html.ActionLink("Esqueceu sua senha?", "ForgotPassword", "Account")
                                </p>
                            }
                            @{
                                var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes().ToList();
                                if (loginProviders.Any())
                                {
                                    using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = ViewBag.ReturnUrl }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="row text-center">
                                            <div id="socialLoginList">
                                                <p>
                                                    @foreach (AuthenticationDescription p in loginProviders)
                                                    {
                                                        <button type="submit" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType"
                                                                class="btn btn-block btn-social btn-@p.AuthenticationType.ToLowerInvariant()">
                                                            <span class="fa fa-@p.AuthenticationType.ToLowerInvariant()"></span> Entre com @p.Caption
                                                        </button>
                                                    }
                                                </p>
                                            </div>
                                        </div>
                                    }
                                }
                            }

                        </div>
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="panel panel-default">
                        <div class="panel-heading">MENU</div>
                        <div class="panel-body">
                            <ul style="margin-bottom: 0;">
                                <li style="margin-bottom: 15px;" ng-if="ctrl.indicacoesAConfirmar > 0"><b><a href="@Url.Action("IndicacoesAConfirmar", "Home")">Você possui {{ctrl.indicacoesAConfirmar}} {{"indicaç"+(ctrl.indicacoesAConfirmar === 1 ? "ão" : "ões")}} a confirmar!</a></b></li>
                                @if (Request.IsAuthenticated)
                                {
                                    if (User.IsInRole("ADMIN") || User.IsInRole("DIRETOR") || User.IsInRole("DELEGADO"))
                                    {
                                        <li>@Html.ActionLink("Cad. Regionais", "Index", "Regional")</li>
                                        <li>@Html.ActionLink("Cad. Associados", "Index", "Usuario")</li>
                                    }
                                    if (User.IsInRole("ADMIN") || User.IsInRole("DIRETOR"))
                                    {
                                        <li>@Html.ActionLink("Cad. Categorias de artigos", "Index", "CategoriaArtigo")</li>
                                        <li>@Html.ActionLink("Cad. Artigos", "Index", "Artigo")</li>
                                        <li>@Html.ActionLink("Cad. Notícias", "Index", "Noticia")</li>
                                        <li>@Html.ActionLink("Cad. Votações", "Index", "Votacao")</li>
                                        <li>@Html.ActionLink("Cad. Benefícios", "Index", "Beneficio")</li>
                                    }
                                    if (User.IsInRole("ADMIN"))
                                    {
                                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                                    }

                                    <li>@Html.ActionLink("Meus dados", "Edit", "Account")</li>
                                }
                            </ul>
                            <hr />
                            <ul style="margin-bottom: 0;">
                                <li>@Html.ActionLink("Situação", "Index", "Situacao")</li>
                            </ul>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</script>

@section styles {
    @Styles.Render("~/cssBundles/angularForm")
    @Styles.Render("~/cssBundles/inicio")
    @Styles.Render(BundleConfig.BundleStylesDataTables)
}
@section dependencies {
    @Scripts.Render("~/bundles/inicio")
}
@section scripts {
    @if (action == "Index")
    {
        <script type="text/javascript">
            (function () {
                angular.module("acerva")
                    .constant("ROTAS", {
                        buscaNoticias: "@Url.Action("BuscaNoticias")",
                        buscaIndicacoesAConfirmar: "@Url.Action("BuscaIndicacoesAConfirmar")"
                    });
            })();
        </script>
    }
    else
    {
        var url = Url.Action("Index") + "#/" + action + "/" + id;
        <script type="text/javascript">
            (function () {
                window.location = '@url';
            })();
        </script>
    }
}

Acerva.Web/Views/Home/IndicacoesAConfirmar.cshtml
@{
    ViewBag.Title = "Indicações a confirmar";
    ViewBag.AngularApp = "acerva.indicacoes";
}

<h4>@ViewBag.Title</h4>
<h5>@ViewBag.Message</h5>

<div ng-view ng-cloak></div>
@Html.AntiForgeryToken()

<script type="text/ng-template" id="index.html">
    <ul class="list-group">
        <li class="list-group-item clearfix" ng-repeat="usuario in ctrl.indicacoesAConfirmar track by usuario.id">
            {{usuario.name}}
            <span class="label label-primary">{{usuario.nomeRegional}}</span>
            <div class="pull-right">
                <a class="btn btn-success btn-xs" ng-click="ctrl.confirmaIndicacao(usuario.id)">Confirmar indicação</a>
                <a class="btn btn-danger btn-xs"
                   acerva-confirm
                   confirm-action="ctrl.declinaIndicacao(usuario.id)"
                   confirm-window-type="danger"
                   confirm-text="Confirma a recusa da indicação de {{ usuario.name }}?">Recusar indicação</a>
            </div>
        </li>
    </ul>
</script>

@section styles {
    @Styles.Render("~/cssBundles/angularForm")
    @Styles.Render(BundleConfig.BundleStylesDataTables)
}

@section dependencies {
    @Scripts.Render("~/bundles/indicacoes")
}

@section scripts {
    <script type="text/javascript">
        (function () {
            angular.module("acerva")
                .constant("ROTAS", {
                    buscaIndicacoesAConfirmar: "@Url.Action("BuscaIndicacoesAConfirmar")",
                    confirmaIndicacao: "@Url.Action("ConfirmDesignation", "Account")",
                    declinaIndicacao: "@Url.Action("DenyDesignation", "Account")"
                });
        })();
    </script>
}

Acerva.Web/Views/Home/_PaginaInicial.cshtml
@{
    ViewBag.Title = "Bem vindo ao site da ACervA Carioca!";
}
<h3>@ViewBag.Title</h3>

<div class="container-noticias" ng-repeat="noticia in ctrl.listaNoticias ">
    <h4 class="titulo text-primary"><span class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span> {{noticia.titulo}}</h4>
    <span ng-bind-html="noticia.textoHtml"></span>
    <div ng-if="noticia.anexos.length > 0">
        <hr />
        <h5>Anexos</h5>
        <ul>
            <li ng-repeat="anexo in noticia.anexos" style="margin-bottom: 10px;">
                <a ng-href="@Url.Content("~/Content/Aplicacao/anexos/noticias/")/{{noticia.codigo}}/{{anexo.nomeArquivo}}" target="_new">{{anexo.titulo}}</a>
            </li>
        </ul>
    </div>
</div>